In [1]:
pip install Numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


Type of Array:

In [72]:
import numpy as np
oneD=np.array([1,2,3,4,5])
print("array:", oneD)
print("shape:", oneD.shape)

array: [1 2 3 4 5]
shape: (5,)


In [3]:
twoD=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("array:\n",twoD)
print("shape:", twoD.shape)


array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (3, 3)


In [4]:
# Shape: (2,2,2) (2 blocks, 2 rows, 2 columns)
threeD=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("array:\n",threeD)
print("shape:",threeD.shape)

array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape: (2, 2, 2)


1.1 Array Creation

Creating an Array from a List

In [7]:
# A NumPy array can be created directly from a Python list using np.array()
list_data=[1,2,3,4,5]
array_frm_lst=np.array(list_data)
print(array_frm_lst)

[1 2 3 4 5]


Creating an Array from a Tuple

In [8]:
tuple_data=(1,2,3,4,5)
array_frm_tpl=np.array(tuple_data)
print(array_frm_tpl)


[1 2 3 4 5]


Creating an Array from Another Array

In [13]:
source_array=np.array([1,2,3,4,5])
#to creates a seprate copy
new_array=np.array(source_array) 
print(new_array)

# .copy() method to explicitly copy an array
copy_array=source_array.copy()
print("Using copy method:", copy_array)

[1 2 3 4 5]
Using copy method: [1 2 3 4 5]


Creating Array using arange() -- 
np.arange(start, stop, step)
start: The beginning value (default is 0).
stop: The end value (exclusive).
step: The gap between numbers.


In [31]:
range_array=np.arange(1,11,2) #(start,upto,step)
print(range_array)

[1 3 5 7 9]


Creating an Array using linspace() --
np.linspace(start,stop,num)
start: The beginning value.
stop: The end value (included by default).
num: The total number of values to generate.



In [16]:
# The linspace() function generates an array with evenly spaced values between a start and stop point.
linspace_array=np.linspace(0,5,5) # 5 values between 0 and 5
print(linspace_array)

[0.   1.25 2.5  3.75 5.  ]


Creating an Arrau using Randon Values

In [19]:
random_array=np.random.rand(3,3) 
#rand will generate floting-point numbers
print(random_array)

random_array=np.random.randint(0,5,(3,3))
print("integer Randon Array", random_array)

[[0.89157645 0.52474014 0.96551488]
 [0.89779679 0.67519095 0.80581977]
 [0.65794713 0.70745339 0.25350873]]
integer Randon Array [[3 3 3]
 [2 4 1]
 [3 3 3]]


Creating an array from a file

In [24]:
# numpy can also create arrays from external files - CSV or text
file_array=np.loadtxt("D:/python_practical/numbertext.txt")
print(file_array)

int_array=file_array.astype(int)
print("Array in INT formt:", int_array)

[ 1.1  2.1  3.1  4.1  5.1  6.1  7.1  8.1  9.1 10.1]
Array in INT formt: [ 1  2  3  4  5  6  7  8  9 10]


Creating Special Arrays (zero, one, identity)

In [30]:
#np.zeros(shape)
#np.ones(shape)
#np.eye(size)
# np.zeros() and np.ones() expects the shape as a tuple (3,3), not separate arguments
zero_array=np.zeros((3,3))
print("Zeros Array:",zero_array)
one_array=np.ones((2,5))
print("Ones Array:",one_array)
identity_matrix=np.eye(3)
print("Identity Matrix:",identity_matrix)


Zeros Array: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Identity Matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.2 Array Indexing and Slicing in Numpy

1.2.1 Indexing - Accessing Elements

In [73]:
# 1D array indexing
array=np.array([1,2,3,4,5])
print(array[0]) # 1st element
print(array[2]) # 3rd element
print(array[-1]) # last element

1
3
5


In [49]:
twoDarray=np.random.randint(1,3,(3,3))
print("2d matrix:", array)
print(twoDarray[0])
print(twoDarray[1,2]) # element at row index 1, column index 2
print(twoDarray[0,0]) # 1st element
print(twoDarray[-1,-1]) # last element

2d matrix: [[1 1 1]
 [1 2 2]
 [1 1 1]]
[2 2 1]
1
2
1


In [52]:
threeDarray = np.array([[[1, 2, 3], [4, 5, 6]], 
                   [[7, 8, 9], [10, 11, 12]]])
print(threeDarray.shape)
print(threeDarray[0,1,2]) # 1st dept, 2nd row, 3rd column


(2, 2, 3)
6


1.2.2 Slicing Array - to extracting parts of array


array[start:stop:step] 
start: Start index (default = 0).
stop: Stop index (exclusive).
step: Step size (default = 1).


In [53]:
#1D array slicing
array=np.array([1,2,3,4,5])
print(array[1:4]) # elements from index 1 to 3
print(array[:3]) # upto 2
print(array[3:])# from 3 to end
print(array[::2])# every 2nd element
print(array[::-1])# reverse

[2 3 4]
[1 2 3]
[4 5]
[1 3 5]
[5 4 3 2 1]


In [57]:
#2D array slicing -- slice rows & columns seperately
twoarray=np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
print(twoarray[:2,1:])# first 2 rows, column from index 1 onwards
print(twoarray[:,0]) # first column
print(twoarray[0,:])# first row
print(twoarray[::-1,::-1]) # reverse the matrix
print(twoarray[::-1,])#reverse the row
print(twoarray[:,::-1])#reverse the column

[[2 3]
 [5 6]]
[1 4 7]
[1 2 3]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [59]:
#3d slicing array -- array[depth_start:depth_stop, row_start:row_stop, col_start:col_stop]
threeDarray=np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
                      [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(threeDarray)
print(threeDarray[0,1,:])#1st depth, 2nd row, all column
print(threeDarray[:1,:,:])#frist depth, all rows, all columns
print(threeDarray[:,0:2,1:3])#both depth, 1st and 2nd row, 2nd and 3rd column

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
[4 5 6]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[ 2  3]
  [ 5  6]]

 [[11 12]
  [14 15]]]


Boolean Indexing - retrieve elements bsed on a condition

In [60]:
arr=np.array([1,2,3,4,5])
print(arr[arr>2]) 

[3 4 5]


1.3 Array Operations

1.3.1 Basic Mathematical Operations -- NumPy allows performing arithmetic operations directly on arrays

In [67]:
#using direct operation
a=np.array([1,2,3,4,5])
b=np.array([10,20,30,40,50])

print(a+b)
print(b-a)
print(a*b)
print(a/b)

# Scalar Operations
print(a+5)
print(a*5)

[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]
[ 6  7  8  9 10]
[ 5 10 15 20 25]


In [74]:
#using function
a=np.array([1,2,3,4,5])
b=np.array([10,20,30,40,50])
c=np.add(a,b)
print(c)

[11 22 33 44 55]


1.3.2 Element-wise Operations 

In [68]:
print(a**2) #square each element
print(a%3) #Modulus operation
print(a//3) #floor division 

[ 1  4  9 16 25]
[1 2 0 1 2]
[0 0 1 1 1]


In [69]:
# Universal Fuctions (ufunc)
print(np.sqrt(a)) #square root
print(np.exp(a)) #exponential (e^x)
print(np.log(a)) #Logaritham
print(np.sin(a)) #sine fun
print(np.cos(a)) #cos

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


1.3.3 Aggregation Functions -- summarize data accross an array

In [70]:
print(np.sum(a)) # sum of all elements
print(np.mean(a))
print(np.median(a))
print(np.min(a))
print(np.max(a))

15
3.0
3.0
1
5


In [71]:
# aggregations in multi-D arrays or specific axes
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(matrix, axis=0)) # sum of all columns
print(np.sum(matrix, axis=1)) # sum of all rows


[12 15 18]


1.3.4 Brodcating (operation with different shapes)

In [76]:
#same size arrays
array=np.array([[1,2,3],[4,5,6]])
print(array+10) # adds 10 to each element

[[11 12 13]
 [14 15 16]]


In [77]:
#brodcating with different arrays:
arr1=np.array([[1],[2],[3]]) #shape(3,1)
arr2=np.array([10,20,30]) #shape(3,)
print(arr1+arr2)
# The broadcasting rules are:
# 1.If the two arrays have different dimensions, NumPy automatically expands the smaller array’s shape.
#2.If a dimension has size 1, NumPy duplicates its values along that dimension to match the larger array.


[[11 21 31]
 [12 22 32]
 [13 23 33]]


1.3.5 Boolean Operations

In [78]:
arr = np.array([1, 2, 3, 4, 5])
print(arr > 3)  # Boolean array
print(arr[arr > 3])  # Filter elements greater than 3

[False False False  True  True]
[4 5]


1.4 Array Manipulations

1.4.1 Changing shape of an array

In [81]:
#reshape()--function allows us to change the shape of an array without modifying its data
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)  # Convert from (6,) to (2,3)
print(reshaped_arr)
arr = arr.reshape(3, -1)
print(arr)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [82]:
# ravel() - Flatteninf an array
# Converts a multi-dimensional array into a 1D array.
arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened = arr.ravel()
print(flattened)

[1 2 3 4 5 6]


In [83]:
# transpose() – Swap Axes of an Array
transposed = arr.T
print(transposed)

[[1 4]
 [2 5]
 [3 6]]


In [87]:
# swapaxes() – Swap Any Two Axes
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # Shape (2,2,2)
print(arr)
swapped = arr.swapaxes(0, 1)
print(swapped)
print(swapped.shape)  # (2,2,2) → (2,2,2) (axes 0 & 1 swapped)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
(2, 2, 2)


1.4.2 Changing size of an array

In [88]:
# resize() – Change Size with Possible Data Loss
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize((2, 4))  # Expands the shape, fills extra values with 0
print(arr)

[[1 2 3 4]
 [5 6 0 0]]


In [89]:
# expand_dims() – Add an Extra Dimension
arr = np.array([1, 2, 3])
expanded = np.expand_dims(arr, axis=0)  # Convert (3,) → (1, 3)
print(expanded.shape)  # Output: (1,3)

(1, 3)


In [90]:
# squeeze() – Remove Extra Dimensions
arr = np.array([[[1, 2, 3]]])  # Shape (1,1,3)
squeezed = arr.squeeze()
print(squeezed.shape) 

(3,)


1.4.3 Changing Data types of an Array

In [99]:
# concatenate() – Join Arrays Along an Axis
a = np.array([[1, 2]])
b = np.array([[5, 6]])
Colcon = np.concatenate((a, b), axis=1)
print(Colcon)
rowcon = np.concatenate((a, b), axis=0)
print(rowcon)

[[1 2 5 6]]
[[1 2]
 [5 6]]


In [100]:
# split() – Split an Array into Multiple Arrays
arr = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.split(arr, 3)
print(split_arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


1.5 Loading and Saving Data to files using NumPy

In [103]:
#Save as a Binary File (.npy)
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
np.save("D:/python_practical/data.npy", arr)  # Saves as a binary file

In [112]:
# Load from a Binary File (.npy)
arr = np.load("D:/python_practical/data.npy")
print(arr)

[1 2 3 4 5]


In [104]:
# Save Multiple Arrays in One File (.npz)
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])
np.savez("D:/python_practical/multiple_arrays.npz", a=arr1, b=arr2)

In [113]:
#  Load Multiple Arrays (.npz)
data = np.load("D:/python_practical/multiple_arrays.npz")
print(data["a"])  # Access stored arrays
print(data["b"])

[1 2 3]
[10 20 30]


In [107]:
# Save as a Text File (.txt or .csv)
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.savetxt("D:/python_practical/datatext.txt", arr, delimiter=",")  # Saves as CSV

In [114]:
# Load from a Text File (.txt or .csv)
arr = np.loadtxt("D:/python_practical/datatext.txt", delimiter=",")
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]
