In [1]:
1+3


4

In [2]:
x = int (input("please enter an integer :"))
if x>0:
    print("weather is hot")
elif x==0:
    print("weather is good to go")

elif x<0:
    print("weather is too cold")


weather is hot


In [3]:
words =["ghf","gas","tgf"]
for w in words:
    print(w,':', len(w))


ghf : 3
gas : 3
tgf : 3


In [4]:
tax = 12.5/100
price =100.50
x=price*tax
print(x)
print(price +x)
round(x,2)

12.5625
113.0625


12.56

In [5]:
print("""\
hello 
hai
bye


""")

hello 
hai
bye





In [6]:
users = {'abc':'active','cde':'inactive','fgh':'inactive'}
for user, status in users.copy().items():
    if status == 'inactive':
        del users[user]
print(users)


{'abc': 'active'}


In [7]:
pip install pandas

In [8]:
import pandas as pd

In [9]:
df = pd.read_csv(r"C:\Users\rmane\Downloads\new_york.csv")
print(df)

       Unnamed: 0        id       neighbourhood  latitude  longitude  \
0               0      2595             Midtown  40.75362  -73.98377   
1               1      3831            Brooklyn  40.68514  -73.95976   
2               2      5099           Manhattan  40.74767  -73.97500   
3               3      5121  Bedford-Stuyvesant  40.68688  -73.95596   
4               4      5178           Manhattan  40.76489  -73.98493   
...           ...       ...                 ...       ...        ...   
17609       35587  30561918            Brooklyn  40.64954  -74.00166   
17610       35588  30561958     Lower East Side  40.72149  -73.98918   
17611       35592  30562589            Brooklyn  40.64487  -73.94711   
17612       35594  30565063            Bushwick  40.70279  -73.91347   
17613       35596  30565284             Jamaica  40.65861  -73.73672   

             room_type   price  days_occupied_in_2019  minimum_nights  \
0      Entire home/apt  225.00                   15.0         

In [10]:
df = pd.read_fwf(r"C:\Users\rmane\Downloads\text.txt", delimiter\)
print(df)

SyntaxError: unexpected character after line continuation character (3354318635.py, line 1)

In [ ]:
pip install openpyxl

In [ ]:
pip install --upgrade pip

In [105]:
f=open(r"C:\Users\rmane\Downloads\new_york.csv")
print(f.readline())
f.readline()

,id,neighbourhood,latitude,longitude,room_type,price,days_occupied_in_2019,minimum_nights,number_of_reviews,reviews_per_month,availability_2020



'0,259'

In [125]:

#reading text files using read(),readline(),readlines()


f=open("file1.txt","w")
L= ["this is delhi\n","this is hyd\n","this is ts\n"]
f.write("hello all\n")
f.writelines(L)


f=open("file1.txt","r+")
print("op of read fn is")
print(f.read())
print()

f.seek(0)
print("op of readline fn is ")
print(f.readline())
print()

f.seek(0)
print("op of read(9) fn is ")
print(f.read(9))
print()

f.seek(0)
print("op of readline(9) fn is ")
print(f.readline(9))
print()

f.seek(0)
print("op of readlines fn is ")
print(f.readlines())
print()

op of read fn is
hello all
this is delhi
this is hyd
this is ts


op of readline fn is 
hello all


op of read(9) fn is 
hello all

op of readline(9) fn is 
hello all

op of readlines fn is 
['hello all\n', 'this is delhi\n', 'this is hyd\n', 'this is ts\n']



In [ ]:
#writing text file using write(),writelines()

f= open(r"C:\Users\rmane\Downloads\text.txt","w")
for i in range(2):
    word= input("enter the word")
    f.write(word)
    f.write("\n")
print("data is entered")
f.close()
f=open(r"C:\Users\rmane\Downloads\text.txt")
print(f.read(),"these are my filecontent")



data is entered
cfgh
gfvfbg
vcde
bgtf
cat
bat
 these are my filecontent


In [ ]:
#writing file using append mode

f=open(r"C:\Users\rmane\Downloads\text.txt","a")

list=[]
for i in range(2):
    word=input("enter the word")
    list.append(word + '\n')
f.writelines(list)
f.close()
print("data is entered")
f=open(r"C:\Users\rmane\Downloads\text.txt",'r')
print(f.read())


data is entered
cfgh
gfvfbg
vcde
bgtf
cat
bat
var
fat
zae
zab



In [166]:
with open(r"C:\Users\rmane\Downloads\text.txt",'r') as f:
    data = f.read()
    print(data)

cfgh
gfvfbg
vcde
bgtf
cat
bat
var
fat
zae
zab



In [167]:
#importing csv module
import csv
#csv file name
filename="newyork.csv"

columns=[]
rows=[]

#reading csv file
with open(filename,'r')
    #creating a csv reader object




In [ ]:
# importing the csv module
import csv
# field names
fields = ['Name', 'Branch', 'Year', 'CGPA']
# data rows of csv file
rows = [['Nikhil', 'COE', '2', '9.0'],
        ['Sanchit', 'COE', '2', '9.1'],
        ['Aditya', 'IT', '2', '9.3'],
        ['Sagar', 'SE', '1', '9.5'],
        ['Prateek', 'MCE', '3', '7.8'],
        ['Sahil', 'EP', '2', '9.1']]
# name of csv file
filename = "university_records.csv"
# writing to csv file
with open(filename, 'w') as csvfile:
    # creating a csv writer object
    csvwriter = csv.writer(csvfile)
    # writing the fields
    csvwriter.writerow(fields)
    # writing the data rows
    csvwriter.writerows(rows)
with open(r"university_records.csv",'r') as f:
    data = f.read()
    print(data)


Name,Branch,Year,CGPA

Nikhil,COE,2,9.0

Sanchit,COE,2,9.1

Aditya,IT,2,9.3

Sagar,SE,1,9.5

Prateek,MCE,3,7.8

Sahil,EP,2,9.1




In [ ]:
#open csv file for reading 
with open("university_records.csv",'r') as f:
#create a csv reader with dict reader
    csv_reader=csv.DictReader(f)
    data_list=[]
    for row in csv_reader:
        data_list.append(row)
for data in data_list:
    print(data)
    

{'Name': 'Nikhil', 'Branch': 'COE', 'Year': '2', 'CGPA': '9.0'}
{'Name': 'Sanchit', 'Branch': 'COE', 'Year': '2', 'CGPA': '9.1'}
{'Name': 'Aditya', 'Branch': 'IT', 'Year': '2', 'CGPA': '9.3'}
{'Name': 'Sagar', 'Branch': 'SE', 'Year': '1', 'CGPA': '9.5'}
{'Name': 'Prateek', 'Branch': 'MCE', 'Year': '3', 'CGPA': '7.8'}
{'Name': 'Sahil', 'Branch': 'EP', 'Year': '2', 'CGPA': '9.1'}


In [12]:
import pandas as pd
df= pd.read_csv("university_records.csv")
print(df)
names =df['Name']
print(names)


      Name Branch  Year  CGPA
0   Nikhil    COE     2   9.0
1  Sanchit    COE     2   9.1
2   Aditya     IT     2   9.3
3    Sagar     SE     1   9.5
4  Prateek    MCE     3   7.8
5    Sahil     EP     2   9.1
0     Nikhil
1    Sanchit
2     Aditya
3      Sagar
4    Prateek
5      Sahil
Name: Name, dtype: object


In [50]:
import pandas as pd
mydict = [
    {'branch': 'COE', 'cgpa': '9.0', 'name': 'Nikhil', 'year': '2'},
    {'branch': 'COE', 'cgpa': '9.1', 'name': 'Sanchit', 'year': '2'},
    {'branch': 'IT', 'cgpa': '9.3', 'name': 'Aditya', 'year': '2'},
    {'branch': 'SE', 'cgpa': '9.5', 'name': 'Sagar', 'year': '1'},
    {'branch': 'MCE', 'cgpa': '7.8', 'name': 'Prateek', 'year': '3'},
    {'branch': 'EP', 'cgpa': '9.1', 'name': 'Sahil', 'year': '2'}
]

# Create a DataFrame from the list of dictionaries
df = pd.DataFrame(mydict)

# Write the DataFrame to a CSV file
df.to_csv('output.csv', index=False)
print(df)


  branch cgpa     name year
0    COE  9.0   Nikhil    2
1    COE  9.1  Sanchit    2
2     IT  9.3   Aditya    2
3     SE  9.5    Sagar    1
4    MCE  7.8  Prateek    3
5     EP  9.1    Sahil    2


In [54]:
# importing the csv module
import csv

# field names
fields = ['Email']

# data rows of csv file
rows = [ ['nikhil.gfg@gmail.com'],
        [ 'sanchit.gfg@gmail.com'],
        [ 'aditya.gfg@gmail.com'],
        [ 'sagar.gfg@gmail.com'],
        ['prateek.gfg@gmail.com'],
        [ 'sahil.gfg@gmail.com']]

# name of csv file
filename = "email_records.csv"

# writing to csv file
with open(filename, 'w') as csvfile:
    # creating a csv writer object
    csvwriter = csv.writer(csvfile)
    
    # writing the fields
    csvwriter.writerow(fields)
    
    # writing the data rows
    csvwriter.writerows(rows)




<_io.TextIOWrapper name='email_records.csv' mode='w' encoding='cp1252'>


In [58]:
#writing json to a file using json.dumps()

import json
dict={
    "name":"manu",
    "id" : "102",
    "sub" : "css"
}
json_object=json.dumps(dict,indent=3)
with open("file1.json","w") as details:
    details.write(json_object)

In [62]:
#writing json to a file using json.dump()

import json
dict={
    "name":"akhil",
    "id":"103",
    "sub":"csv"
}
with open ("sample.json","w") as simple:
    json.dump(dict,simple)

In [64]:
#reading json file from a file using json.load()

import json
with open("sample.json",'r') as op:
    json_object=json.load(op)
print(json_object)
print(type(json_object))


{'name': 'akhil', 'id': '103', 'sub': 'csv'}
<class 'dict'>


In [ ]:
#creating a pandas dataframe
import pandas as pd
list=[['akhil',30,'male'],['manu',26,'female']]
df =pd.DataFrame(list,columns=["name","age","gender"])
df



name  age  gender
0  akhil   30    male
1   manu   26  female

In [67]:
#creating and importing a numpy array using np.array()
import numpy as np
mat_array=np.array([[2,2,4],
                    [3,5,7],
                    [6,7,3]])
print(mat_array)

[[2 2 4]
 [3 5 7]
 [6 7 3]]


In [68]:
import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}
df = pd.DataFrame(data)

# Using .loc[] to select rows by label
row_by_label = df.loc[1]  # Selects the row with index label 1 (Bob's data)

# Using .iloc[] to select rows by position
row_by_position = df.iloc[1]  # Selects the second row (Bob's data)

print("Row by label:\n", row_by_label)
print("Row by position:\n", row_by_position)

Row by label:
 Name    Bob
Age      30
Name: 1, dtype: object
Row by position:
 Name    Bob
Age      30
Name: 1, dtype: object


In [69]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [70]:
pip install pytest

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [84]:
#math_functions.py
def add(x, y):
    return x + y

def subtract(x, y):
    return x - y




In [2]:
import math_functions

def result_add():
    assert math_functions.add(3,4)==7
def result_sub():
    assert math_functions.sub(7,4)==3


ModuleNotFoundError: No module named 'math_functions'

In [85]:
import os
print(os.getcwd())

c:\Users\rmane\.vscode\cli


In [11]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.
